name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        hacking=/metadata/instance/compute/tagsList?api-version=2019-06-04
        curl -H "Metadata: true" http://169.254.169.254$hacking
      
      

