name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        hacking=/metadata/instance/compute/storageProfile?api-version=2019-06-01
        curl -H "Metadata: true" http://127.0.1
