name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2.0.0
    - name: Cache
    - run: cd .. && ls
      with:
        path: /test
        key: 123

